"""initial_schema_uuid

Revision ID: a3c6f868712d
Revises:
Create Date: 2026-03-21 19:23:47.657798

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3c6f868712d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "crypto_orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("package_type", sa.String(length=50), nullable=False),
        sa.Column("amount_usdt", sa.Float(), nullable=False),
        sa.Column("wallet_address", sa.String(length=255), nullable=False),
        sa.Column("tron_dealer_order_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", "EXPIRED", name="crypto_order_status"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("tx_hash", sa.String(length=255), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crypto_orders_user_id"), "crypto_orders", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_crypto_orders_wallet_address"), "crypto_orders", ["wallet_address"], unique=False
    )
    op.create_table(
        "crypto_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("wallet_address", sa.String(length=255), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("tx_hash", sa.String(length=255), nullable=False),
        sa.Column("token_symbol", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "FAILED", name="crypto_transaction_status"),
            nullable=False,
        ),
        sa.Column("confirmations", sa.Integer(), nullable=False),
        sa.Column("raw_payload", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crypto_transactions_tx_hash"), "crypto_transactions", ["tx_hash"], unique=True
    )
    op.create_index(
        op.f("ix_crypto_transactions_user_id"), "crypto_transactions", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_crypto_transactions_wallet_address"),
        "crypto_transactions",
        ["wallet_address"],
        unique=False,
    )
    op.create_table(
        "data_packages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "package_type",
            sa.Enum("BASIC", "ESTANDAR", "AVANZADO", "PREMIUM", "UNLIMITED", name="package_type"),
            nullable=False,
        ),
        sa.Column("data_limit_bytes", sa.BigInteger(), nullable=False),
        sa.Column("data_used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("stars_paid", sa.Integer(), nullable=False),
        sa.Column(
            "purchased_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("telegram_payment_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_data_packages_user_id"), "data_packages", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("amount_usd", sa.Float(), nullable=False),
        sa.Column("gb_purchased", sa.Float(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("TELEGRAM_STARS", "CRYPTO_USDT", "CRYPTO_BSC", name="payment_method"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "COMPLETED", "FAILED", "EXPIRED", name="payment_status"),
            nullable=False,
        ),
        sa.Column("crypto_address", sa.String(length=255), nullable=True),
        sa.Column("crypto_network", sa.String(length=50), nullable=True),
        sa.Column("telegram_star_invoice_id", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transaction_hash", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "subscription_plans",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "plan_type",
            sa.Enum("ONE_MONTH", "THREE_MONTHS", "SIX_MONTHS", name="plan_type"),
            nullable=False,
        ),
        sa.Column("stars_paid", sa.Integer(), nullable=False),
        sa.Column("payment_id", sa.String(length=255), nullable=False),
        sa.Column(
            "starts_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index(
        op.f("ix_subscription_plans_user_id"), "subscription_plans", ["user_id"], unique=False
    )
    op.create_table(
        "subscription_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("plan_type", sa.String(), nullable=False),
        sa.Column("amount_stars", sa.Integer(), nullable=False),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "COMPLETED", "EXPIRED", "FAILED", name="subscription_transaction_status"
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_subscription_transactions_transaction_id"),
        "subscription_transactions",
        ["transaction_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_subscription_transactions_user_id"),
        "subscription_transactions",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("balance_gb", sa.Float(), nullable=False),
        sa.Column("total_purchased_gb", sa.Float(), nullable=False),
        sa.Column("referral_code", sa.String(length=20), nullable=False),
        sa.Column("referred_by", sa.Uuid(), nullable=True),
        sa.Column("referral_credits", sa.BigInteger(), nullable=False),
        sa.Column("purchase_count", sa.BigInteger(), nullable=False),
        sa.Column("loyalty_bonus_percent", sa.BigInteger(), nullable=False),
        sa.Column("welcome_bonus_used", sa.Boolean(), nullable=False),
        sa.Column("referred_users_with_purchase", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_referral_code"), "users", ["referral_code"], unique=True)
    op.create_index(op.f("ix_users_referred_by"), "users", ["referred_by"], unique=False)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "vpn_keys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("key_type", sa.Enum("OUTLINE", "WIREGUARD", name="key_type"), nullable=False),
        sa.Column("key_data", sa.Text(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_bytes", sa.Integer(), nullable=False),
        sa.Column("data_limit_bytes", sa.Integer(), nullable=False),
        sa.Column("billing_reset_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vpn_keys_external_id"), "vpn_keys", ["external_id"], unique=False)
    op.create_index(op.f("ix_vpn_keys_user_id"), "vpn_keys", ["user_id"], unique=False)
    op.create_table(
        "webhook_tokens",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.String(length=50), nullable=False),
        sa.Column("extra_data", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_tokens_token_hash"), "webhook_tokens", ["token_hash"], unique=True
    )
    op.create_table(
        "consumption_billings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "closed", "paid", name="billing_status_enum"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mb_consumed", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("total_cost_usd", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("price_per_mb_usd", sa.Numeric(precision=20, scale=12), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consumption_billings_status"), "consumption_billings", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_consumption_billings_user_id"), "consumption_billings", ["user_id"], unique=True
    )
    op.create_table(
        "referrals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("referrer_id", sa.UUID(), nullable=False),
        sa.Column("referred_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("bonus_applied", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["referred_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_referrals_referred_id"), "referrals", ["referred_id"], unique=True)
    op.create_index(op.f("ix_referrals_referrer_id"), "referrals", ["referrer_id"], unique=False)
    op.create_table(
        "tickets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("status", sa.String(length=15), server_default="open", nullable=False),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.BigInteger(), nullable=True),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.telegram_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallet_pools",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column("original_user_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reused_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("reused_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["original_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reused_by_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_wallet_pools_original_user_id"), "wallet_pools", ["original_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_pools_reused_by_user_id"),
        "wallet_pools",
        ["reused_by_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_wallet_pools_status"), "wallet_pools", ["status"], unique=False)
    op.create_index(
        op.f("ix_wallet_pools_wallet_address"), "wallet_pools", ["wallet_address"], unique=True
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("balance_usdt", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_received_usdt", sa.Float(), nullable=False),
        sa.Column("transaction_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=True)
    op.create_index(op.f("ix_wallets_status"), "wallets", ["status"], unique=False)
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=True)
    op.create_table(
        "consumption_invoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("billing_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("amount_usd", sa.Numeric(precision=20, scale=6), nullable=False),
        sa.Column("wallet_address", sa.String(length=42), nullable=False),
        sa.Column(
            "payment_method", sa.Enum("stars", "crypto", name="payment_method_enum"), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "paid", "expired", name="invoice_status_enum"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("transaction_hash", sa.String(length=66), nullable=True),
        sa.Column("telegram_payment_id", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["billing_id"], ["consumption_billings.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.telegram_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consumption_invoices_billing_id"),
        "consumption_invoices",
        ["billing_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_invoices_expires_at"),
        "consumption_invoices",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_invoices_status"), "consumption_invoices", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_consumption_invoices_telegram_payment_id"),
        "consumption_invoices",
        ["telegram_payment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_invoices_transaction_hash"),
        "consumption_invoices",
        ["transaction_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_invoices_user_id"), "consumption_invoices", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_consumption_invoices_wallet_address"),
        "consumption_invoices",
        ["wallet_address"],
        unique=False,
    )
    op.create_table(
        "ticket_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("ticket_id", sa.UUID(), nullable=False),
        sa.Column("from_user_id", sa.BigInteger(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("from_admin", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ticket_messages")
    op.drop_index(op.f("ix_consumption_invoices_wallet_address"), table_name="consumption_invoices")
    op.drop_index(op.f("ix_consumption_invoices_user_id"), table_name="consumption_invoices")
    op.drop_index(
        op.f("ix_consumption_invoices_transaction_hash"), table_name="consumption_invoices"
    )
    op.drop_index(
        op.f("ix_consumption_invoices_telegram_payment_id"), table_name="consumption_invoices"
    )
    op.drop_index(op.f("ix_consumption_invoices_status"), table_name="consumption_invoices")
    op.drop_index(op.f("ix_consumption_invoices_expires_at"), table_name="consumption_invoices")
    op.drop_index(op.f("ix_consumption_invoices_billing_id"), table_name="consumption_invoices")
    op.drop_table("consumption_invoices")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_status"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_wallet_pools_wallet_address"), table_name="wallet_pools")
    op.drop_index(op.f("ix_wallet_pools_status"), table_name="wallet_pools")
    op.drop_index(op.f("ix_wallet_pools_reused_by_user_id"), table_name="wallet_pools")
    op.drop_index(op.f("ix_wallet_pools_original_user_id"), table_name="wallet_pools")
    op.drop_table("wallet_pools")
    op.drop_table("tickets")
    op.drop_index(op.f("ix_referrals_referrer_id"), table_name="referrals")
    op.drop_index(op.f("ix_referrals_referred_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index(op.f("ix_consumption_billings_user_id"), table_name="consumption_billings")
    op.drop_index(op.f("ix_consumption_billings_status"), table_name="consumption_billings")
    op.drop_table("consumption_billings")
    op.drop_index(op.f("ix_webhook_tokens_token_hash"), table_name="webhook_tokens")
    op.drop_table("webhook_tokens")
    op.drop_index(op.f("ix_vpn_keys_user_id"), table_name="vpn_keys")
    op.drop_index(op.f("ix_vpn_keys_external_id"), table_name="vpn_keys")
    op.drop_table("vpn_keys")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_referred_by"), table_name="users")
    op.drop_index(op.f("ix_users_referral_code"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_subscription_transactions_user_id"), table_name="subscription_transactions"
    )
    op.drop_index(
        op.f("ix_subscription_transactions_transaction_id"), table_name="subscription_transactions"
    )
    op.drop_table("subscription_transactions")
    op.drop_index(op.f("ix_subscription_plans_user_id"), table_name="subscription_plans")
    op.drop_table("subscription_plans")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_data_packages_user_id"), table_name="data_packages")
    op.drop_table("data_packages")
    op.drop_index(op.f("ix_crypto_transactions_wallet_address"), table_name="crypto_transactions")
    op.drop_index(op.f("ix_crypto_transactions_user_id"), table_name="crypto_transactions")
    op.drop_index(op.f("ix_crypto_transactions_tx_hash"), table_name="crypto_transactions")
    op.drop_table("crypto_transactions")
    op.drop_index(op.f("ix_crypto_orders_wallet_address"), table_name="crypto_orders")
    op.drop_index(op.f("ix_crypto_orders_user_id"), table_name="crypto_orders")
    op.drop_table("crypto_orders")
    # ### end Alembic commands ###
