"""Códigos de error compartidos."""

# Errores de usuario
USER_NOT_FOUND = "USER_NOT_FOUND"
USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
USER_BANNED = "USER_BANNED"

# Errores de claves VPN
VPN_KEY_NOT_FOUND = "VPN_KEY_NOT_FOUND"
VPN_KEY_LIMIT_REACHED = "VPN_KEY_LIMIT_REACHED"
VPN_KEY_ALREADY_EXISTS = "VPN_KEY_ALREADY_EXISTS"
VPN_KEY_GENERATION_FAILED = "VPN_KEY_GENERATION_FAILED"

# Errores de pagos
PAYMENT_NOT_FOUND = "PAYMENT_NOT_FOUND"
PAYMENT_ALREADY_COMPLETED = "PAYMENT_ALREADY_COMPLETED"
PAYMENT_EXPIRED = "PAYMENT_EXPIRED"
PAYMENT_FAILED = "PAYMENT_FAILED"
INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"

# Errores de referidos
REFERRAL_CODE_INVALID = "REFERRAL_CODE_INVALID"
REFERRAL_CODE_ALREADY_USED = "REFERRAL_CODE_ALREADY_USED"
SELF_REFERRAL_NOT_ALLOWED = "SELF_REFERRAL_NOT_ALLOWED"

# Errores de autenticación
AUTH_INVALID_TOKEN = "AUTH_INVALID_TOKEN"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_INVALID_TELEGRAM_DATA = "AUTH_INVALID_TELEGRAM_DATA"
